name: "Who's Your Guru"
favicon: null
layout_spectrum: 0.25236
typography_spectrum: 0.27240952639840543
title: "Who's Your Guru"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.4783284096047282
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
